name: minerva-local
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - notebook
  - ipykernel
  # Libraries
  - numpy
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - timm==0.4.12