name: minerva-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - notebook
  - ipykernel
  # Libraries
  - numpy
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # Crucial: This tells conda to install the GPU kernels
  - timm==0.4.12
  - certifi
  - ca-certificates
  - openssl
  - requests
  - urllib3

variables:
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
  REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt